name: ci
on:
  push:
    branches:
      - "feature/**"
      - "hotfix/**"

  pull_request:
    branches:
      - "develop"
      - "main"

jobs:
  lintTest:
    name: Lint Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.28.0
        run: |
          echo "Running Installing Dependencies ..."
          pnpm i --frozen-lockfile
      - name: Run Lint Test
        run: |
          echo "Running Linting tests ..."
          yarn run lint
        env:
          CI: true
